export const entreprises = [
  {
    id: 1,
    title: 'Bidule',
    etpName: 'John Doe',
    photo: '',
    type: 'social',
    shortPrez: 'blablabla',
    needs: '100 000',
    participation: '20 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id: 2,
    title: 'Machin',
    etpName: 'Jack Bauer',
    photo: '',
    type: 'écologique',
    shortPrez: 'blablabla',
    needs: '300 000',
    participation: '20 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id: 3,
    title: 'Voilà',
    etpName: 'Sarah Key',
    photo: '',
    type: 'éducatif',
    shortPrez: 'blablabla',
    needs: '200 000',
    participation: '20 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id: 4,
    title: 'Ecco',
    etpName: 'Philippa Flop',
    photo: '',
    type: 'social',
    shortPrez: 'blablabla',
    needs: '50 000',
    participation: '20 000',
    rentability: '5000',
    etpCurriculum: 'blablabla',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
];

// ========================= PRODUCTS ===============================

export const products = [
  {
    id_product: 1,
    name: 'poufArtisan1Produit1',
    artisan_id: 1,
    category: 'ameublement',
    type: 'pouf',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Limoges',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id_product: 2,
    name: 'Tabula Artisan2Produit2',
    artisan_id: 2,
    category: 'ameublement',
    type: 'table',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Paris',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id_product: 3,
    name: 'RiArtisan2Produit3',
    artisan_id: 2,
    category: 'ameublement',
    type: 'tabouret',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Stokhölm',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id_product: 4,
    name: 'FraArtisan1Produit4',
    artisan_id: 1,
    category: 'ambiance',
    type: 'parfums',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Grasse',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },

];


export const artisans = [
  {
    id: 1,
    name: 'Willy Muller',   
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Limoges',
  },
  {
    id: 2,
    name: 'Sophie Zama',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
  },
  {
    id: 3,
    name: 'Josy Pelletier',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Auvergne',
  },
  {
    id: 4,
    name: 'Alix Montaigne',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Limoges',
  },
];
