
// ========================= PRODUCTS ===============================

export const products = [
  {
    id_product: 1,
    name: 'poufArtisan1Produit1',
    artisan_id: 1,
    category: 'ameublement',
    type: 'pouf',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Limoges',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id_product: 2,
    name: 'Tabula Artisan2Produit2',
    artisan_id: 2,
    category: 'ameublement',
    type: 'table',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Paris',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id_product: 3,
    name: 'RiArtisan2Produit3',
    artisan_id: 2,
    category: 'ameublement',
    type: 'tabouret',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Stokhölm',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: true,
  },
  {
    id_product: 4,
    name: 'FraArtisan1Produit4',
    artisan_id: 1,
    category: 'ambiance',
    type: 'parfums',
    thumbnail: '',
    photo: '',
    dimensions: '40cmx50cm',
    materials: '100% coton',
    origine: 'Grasse',
    longPrez: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    firstPage: false,
  },

];


export const artisans = [
  {
    id: 1,
    name: 'Willy Muller',   
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Limoges',
    firstPage: true,
  },
  {
    id: 2,
    name: 'Sophie Zama',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: true,
  },
  {
    id: 3,
    name: 'Josy Pelletier',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Auvergne',
    firstPage: false,
  },
  {
    id: 4,
    name: 'Alix Montaigne',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Limoges',
    firstPage: false,
  },
  {
    id: 5,
    name: 'Julia Farra',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: true,
  },
  {
    id: 6,
    name: 'Ludo Riva',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: true,
  },
  {
    id: 7,
    name: 'Lynda Zubi',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
  },
  {
    id: 8,
    name: 'Pamela Rubia',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
  },
  {
    id: 9,
    name: 'Silvia Cecutti',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
  },
  {
    id: 10,
    name: 'Celine Fox',
    presentation: 'ameublementsfsdffdfdsfsdfsdfsffsfsd fsdfdsfsdfdsfdsfdsfsf',
    thumbnail: '',
    photo: '',
    origine: 'Senegal',
    firstPage: false,
  },
];
